In [1]:
import torch
import torch.nn as nn
from torch.nn import functional as F

In [2]:
x = torch.arange(4)
torch.save(x, 'x-file')

In [3]:
x2 = torch.load('x-file')
print(x2)

tensor([0, 1, 2, 3])


In [4]:
y = torch.zeros(4)
torch.save([x, y], 'x_y-file')

In [5]:
x2, y2 = torch.load('x_y-file')
print(x2, y2)

tensor([0, 1, 2, 3]) tensor([0., 0., 0., 0.])


In [6]:
my_dict = {'x':x, 'y':y}
torch.save(my_dict, 'my_dict')
my_dict2 = torch.load('my_dict')
print(my_dict2)

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}


In [9]:
# 加载和保存模型参数
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.out = nn.Linear(256, 10)

    def forward(self, x):
        return self.out(F.relu(self.hidden(x)))

net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)

In [10]:
# 将模型的参数存为mlp.params的文件
torch.save(net.state_dict(), 'mlp.params')

In [11]:
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()  # 进入测试模式

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (out): Linear(in_features=256, out_features=10, bias=True)
)

In [12]:
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])